In [2]:
import pandas as pd

In [3]:
df= pd.read_csv("/content/cleaned_hospital_data.csv")

In [4]:
df_virginia = df[df["State"] == "VA"] #Flitering down to virginia
print(df_virginia.shape)

(2097, 13)

In [5]:
print(df_virginia["Facility Name"].nunique()) #going to see how many unique hospitals are in the Virginia dataset

66

In [6]:
df.head()

,Facility Name,Facility ID,State,Measure Name,Number of Discharges,Excess Readmission Ratio,Number of Readmissions,HCAHPS Measure ID,HCAHPS Question,HCAHPS Answer Description,Patient Survey Star Rating,Number of Completed Surveys,Survey Response Rate Percent
0,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-CABG-HRRP,137.0,0.9531,13,H_COMP_1_STAR_RATING,Nurse communication - star rating,Nurse communication - star rating,3.0,596.0,16.0
1,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-CABG-HRRP,137.0,0.9531,13,H_COMP_2_STAR_RATING,Doctor communication - star rating,Doctor communication - star rating,4.0,596.0,16.0
2,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-CABG-HRRP,137.0,0.9531,13,H_COMP_5_STAR_RATING,Communication about medicines - star rating,Communication about medicines - star rating,3.0,596.0,16.0
3,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-CABG-HRRP,137.0,0.9531,13,H_COMP_6_STAR_RATING,Discharge information - star rating,Discharge information - star rating,4.0,596.0,16.0
4,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-CABG-HRRP,137.0,0.9531,13,H_CLEAN_STAR_RATING,Cleanliness - star rating,Cleanliness - star rating,3.0,596.0,16.0

In [7]:
import sqlite3

conn_va = sqlite3.connect("virginia_hospitals.db")
df_virginia.to_sql("virginia", conn_va, if_exists="replace", index=False)

print("Virginia database created!")

Virginia database created!

In [8]:
query = """
SELECT "Facility Name", AVG("Excess Readmission Ratio") AS avg_excess_readmission_ratio
FROM virginia
GROUP BY "Facility Name"
ORDER BY avg_excess_readmission_ratio DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn_va)
result

#the top 10 worst performing hospitals.

                               Facility Name  avg_excess_readmission_ratio
0                   MARY WASHINGTON HOSPITAL                      1.117780
1                   LEWISGALE MEDICAL CENTER                      1.078240
2                   MARY IMMACULATE HOSPITAL                      1.073367
3                  HENRICO DOCTORS' HOSPITAL                      1.070217
4  BON SECOURS SOUTHAMPTON MEMORIAL HOSPITAL                      1.066250
5   SENTARA NORTHERN VIRGINIA MEDICAL CENTER                      1.055675
6                     STAFFORD HOSPITAL, LLC                      1.052467
7       BON SECOURS SOUTHSIDE MEDICAL CENTER                      1.050700
8                    RUSSELL COUNTY HOSPITAL                      1.050300
9                     SENTARA LEIGH HOSPITAL                      1.045425

In [9]:
query = """
SELECT "Facility Name", AVG("Excess Readmission Ratio") AS avg_excess_readmission_ratio
FROM virginia
GROUP BY "Facility Name"
ORDER BY avg_excess_readmission_ratio ASC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn_va)
result

#the top 10 best performing hospitals.

                             Facility Name  avg_excess_readmission_ratio
0                           AUGUSTA HEALTH                      0.865300
1                   INOVA LOUDOUN HOSPITAL                      0.914625
2                  CARILION MEDICAL CENTER                      0.922240
3  CENTRA HEALTH -  LYNCHBURG GEN HOSPITAL                      0.931940
4             LEWISGALE HOSPITAL ALLEGHANY                      0.937850
5                   INOVA FAIRFAX HOSPITAL                      0.939620
6                INOVA ALEXANDRIA HOSPITAL                      0.940875
7        SOUTHSIDE COMMUNITY HOSPITAL, INC                      0.944867
8      CARILION FRANKLIN MEMORIAL HOSPITAL                      0.946100
9        SENTARA MARTHA JEFFERSON HOSPITAL                      0.947600

In [10]:
print(df_virginia["Patient Survey Star Rating"].isnull().sum())
print(df_virginia["Patient Survey Star Rating"].unique())

0
[4. 2. 3. 5. 1.]

In [11]:
query = """
SELECT "Facility Name", "HCAHPS Question", AVG ("Patient Survey Star Rating") AS avg_rating
FROM virginia
GROUP BY "Facility Name", "HCAHPS Question"
ORDER BY avg_rating ASC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn_va)
result

#patient satisfaction trends at specific Virginia hospitals from worst 10

,Facility Name,HCAHPS Question,avg_rating
0,BON SECOURS ST FRANCIS MEDICAL CENTER,Communication about medicines - star rating,1.0
1,LEWISGALE MEDICAL CENTER,Communication about medicines - star rating,1.0
2,SPOTSYLVANIA REGIONAL MEDICAL CENTER,Communication about medicines - star rating,1.0
3,SPOTSYLVANIA REGIONAL MEDICAL CENTER,Discharge information - star rating,1.0
4,SPOTSYLVANIA REGIONAL MEDICAL CENTER,Doctor communication - star rating,1.0
5,AUGUSTA HEALTH,Cleanliness - star rating,2.0
6,AUGUSTA HEALTH,Quietness - star rating,2.0
7,BON SECOURS MARYVIEW MEDICAL CENTER,Cleanliness - star rating,2.0
8,BON SECOURS MARYVIEW MEDICAL CENTER,Communication about medicines - star rating,2.0
9,BON SECOURS MARYVIEW MEDICAL CENTER,Quietness - star rating,2.0

In [12]:
query = """
SELECT "Facility Name", "HCAHPS Question", AVG ("Patient Survey Star Rating") AS avg_rating
FROM virginia
GROUP BY "Facility Name", "HCAHPS Question"
ORDER BY avg_rating DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn_va)
result

#patient satisfaction trends at specific Virginia hospitals from top 10

,Facility Name,HCAHPS Question,avg_rating
0,CENTRA BEDFORD MEMORIAL HOSPITAL,Discharge information - star rating,5.0
1,CENTRA BEDFORD MEMORIAL HOSPITAL,Doctor communication - star rating,5.0
2,CENTRA BEDFORD MEMORIAL HOSPITAL,Nurse communication - star rating,5.0
3,CENTRA BEDFORD MEMORIAL HOSPITAL,Recommend hospital - star rating,5.0
4,CENTRA BEDFORD MEMORIAL HOSPITAL,Summary star rating,5.0
5,CLINCH VALLEY MEDICAL CENTER,Nurse communication - star rating,5.0
6,COMMUNITY MEMORIAL HOSPITAL,Cleanliness - star rating,5.0
7,COMMUNITY MEMORIAL HOSPITAL,Nurse communication - star rating,5.0
8,INOVA FAIR OAKS HOSPITAL,Recommend hospital - star rating,5.0
9,INOVA FAIRFAX HOSPITAL,Recommend hospital - star rating,5.0

In [13]:
query = """
SELECT "Facility Name", "HCAHPS Question", AVG ("Patient Survey Star Rating") AS avg_rating
FROM virginia
GROUP BY "Facility Name", "HCAHPS Question"
ORDER BY avg_rating DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn_va)
result

,Facility Name,HCAHPS Question,avg_rating
0,CENTRA BEDFORD MEMORIAL HOSPITAL,Discharge information - star rating,5.0
1,CENTRA BEDFORD MEMORIAL HOSPITAL,Doctor communication - star rating,5.0
2,CENTRA BEDFORD MEMORIAL HOSPITAL,Nurse communication - star rating,5.0
3,CENTRA BEDFORD MEMORIAL HOSPITAL,Recommend hospital - star rating,5.0
4,CENTRA BEDFORD MEMORIAL HOSPITAL,Summary star rating,5.0
5,CLINCH VALLEY MEDICAL CENTER,Nurse communication - star rating,5.0
6,COMMUNITY MEMORIAL HOSPITAL,Cleanliness - star rating,5.0
7,COMMUNITY MEMORIAL HOSPITAL,Nurse communication - star rating,5.0
8,INOVA FAIR OAKS HOSPITAL,Recommend hospital - star rating,5.0
9,INOVA FAIRFAX HOSPITAL,Recommend hospital - star rating,5.0

In [17]:
query = """
SELECT "Measure Name", AVG("Excess Readmission Ratio") AS avg_excess_readmission_ratio
FROM virginia
GROUP BY "Measure Name"
ORDER BY avg_excess_readmission_ratio DESC
"""

result = pd.read_sql_query(query, conn_va)
result

#which conditions perform best and worst across Virginia hospitals

             Measure Name  avg_excess_readmission_ratio
0  READM-30-HIP-KNEE-HRRP                      1.018887
1        READM-30-PN-HRRP                      0.999259
2      READM-30-COPD-HRRP                      0.996861
3        READM-30-HF-HRRP                      0.993159
4      READM-30-CABG-HRRP                      0.989775
5       READM-30-AMI-HRRP                      0.986981

In [18]:
df_virginia.to_csv("virginia_hospitals.csv", index=False)