In [161]:
import pandas as pd

In [162]:
df=pd.read_csv("/content/FY_2026_Hospital_Readmissions_Reduction_Program_Hospital.csv")

In [163]:
df.head(5000) # missing values are in number of dischargers, footnote, excess readmission ratio, predicted & expected readmission rate, number of readmissions.

,Facility Name,Facility ID,State,Measure Name,Number of Discharges,Footnote,Excess Readmission Ratio,Predicted Readmission Rate,Expected Readmission Rate,Number of Readmissions,Start Date,End Date
0,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-HIP-KNEE-HRRP,NaN,NaN,0.9875,4.5734,4.6311,Too Few to Report,07/01/2021,06/30/2024
1,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-CABG-HRRP,137.0,NaN,0.9531,10.3960,10.9078,13,07/01/2021,06/30/2024
2,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-AMI-HRRP,273.0,NaN,0.9370,13.2998,14.1948,33,07/01/2021,06/30/2024
3,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-COPD-HRRP,122.0,NaN,0.9823,16.6384,16.9389,19,07/01/2021,06/30/2024
4,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-PN-HRRP,507.0,NaN,0.9871,15.7529,15.9591,79,07/01/2021,06/30/2024
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,"NORTH HAWAII COMMUNITY HOSPITAL, INC",120028,HI,READM-30-COPD-HRRP,NaN,1.0,NaN,NaN,NaN,NaN,07/01/2021,06/30/2024
4996,"NORTH HAWAII COMMUNITY HOSPITAL, INC",120028,HI,READM-30-CABG-HRRP,NaN,5.0,NaN,NaN,NaN,NaN,07/01/2021,06/30/2024
4997,"NORTH HAWAII COMMUNITY HOSPITAL, INC",120028,HI,READM-30-AMI-HRRP,NaN,1.0,NaN,NaN,NaN,NaN,07/01/2021,06/30/2024
4998,ST LUKES MAGIC VALLEY MEDICAL CENTER,130002,ID,READM-30-PN-HRRP,322.0,NaN,0.9310,13.2456,14.2273,38,07/01/2021,06/30/2024
4999,ST LUKES MAGIC VALLEY MEDICAL CENTER,130002,ID,READM-30-HIP-KNEE-HRRP,NaN,1.0,NaN,NaN,NaN,NaN,07/01/2021,06/30/2024

In [164]:
df = df.drop(columns=["Footnote", "Predicted Readmission Rate", "Expected Readmission Rate", "Start Date", "End Date"]) #You dropped the columns because they added no value to the analysis, and the rows because hospitals didn't have enough patients to report data for those conditions, making them unusable.

In [165]:
df.head(2000)

,Facility Name,Facility ID,State,Measure Name,Number of Discharges,Excess Readmission Ratio,Number of Readmissions
0,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-HIP-KNEE-HRRP,NaN,0.9875,Too Few to Report
1,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-CABG-HRRP,137.0,0.9531,13
2,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-AMI-HRRP,273.0,0.9370,33
3,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-COPD-HRRP,122.0,0.9823,19
4,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-PN-HRRP,507.0,0.9871,79
...,...,...,...,...,...,...,...
1995,ADVENTIST HEALTH SONORA,50335,CA,READM-30-CABG-HRRP,NaN,NaN,NaN
1996,ADVENTIST HEALTH SONORA,50335,CA,READM-30-HIP-KNEE-HRRP,NaN,NaN,NaN
1997,ADVENTIST HEALTH SONORA,50335,CA,READM-30-PN-HRRP,385.0,0.9697,52
1998,ADVENTIST HEALTH LODI MEMORIAL,50336,CA,READM-30-HF-HRRP,389.0,1.1077,87
1999,ADVENTIST HEALTH LODI MEMORIAL,50336,CA,READM-30-COPD-HRRP,144.0,0.9720,23

In [166]:
df = df.dropna(subset=["Number of Discharges", "Excess Readmission Ratio", "Number of Readmissions"])

In [167]:
df.head(700)

,Facility Name,Facility ID,State,Measure Name,Number of Discharges,Excess Readmission Ratio,Number of Readmissions
1,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-CABG-HRRP,137.0,0.9531,13
2,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-AMI-HRRP,273.0,0.9370,33
3,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-COPD-HRRP,122.0,0.9823,19
4,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-PN-HRRP,507.0,0.9871,79
5,SOUTHEAST HEALTH MEDICAL CENTER,10001,AL,READM-30-HF-HRRP,653.0,1.0233,136
...,...,...,...,...,...,...,...
1711,PALMDALE REGIONAL MEDICAL CENTER,50204,CA,READM-30-COPD-HRRP,57.0,1.0234,11
1714,PALMDALE REGIONAL MEDICAL CENTER,50204,CA,READM-30-PN-HRRP,182.0,1.0058,33
1716,ALAMEDA HOSPITAL,50211,CA,READM-30-HF-HRRP,99.0,1.0048,18
1721,ALAMEDA HOSPITAL,50211,CA,READM-30-PN-HRRP,196.0,1.0379,37
1722,SHARP CHULA VISTA MEDICAL CENTER,50222,CA,READM-30-PN-HRRP,419.0,0.9821,64

In [168]:
df["Number of Readmissions"] = pd.to_numeric(df["Number of Readmissions"]) #Had to change Number of Readmissions to numeric so it can be used in calculations and analysis

In [169]:
df.dtypes

Facility Name                object
Facility ID                   int64
State                        object
Measure Name                 object
Number of Discharges        float64
Excess Readmission Ratio    float64
Number of Readmissions        int64
dtype: object

In [170]:
df2=pd.read_csv("/content/HCAHPS-Hospital.csv", low_memory=False)

In [171]:
df2.head(5000) #get rid of answer percent footnote, linear mean value, rate percent footnote, start and end date, telephone number,

,Facility ID,Facility Name,Address,City/Town,State,ZIP Code,County/Parish,Telephone Number,HCAHPS Measure ID,HCAHPS Question,...,Patient Survey Star Rating Footnote,HCAHPS Answer Percent,HCAHPS Answer Percent Footnote,HCAHPS Linear Mean Value,Number of Completed Surveys,Number of Completed Surveys Footnote,Survey Response Rate Percent,Survey Response Rate Percent Footnote,Start Date,End Date
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,H_COMP_1_A_P,"Patients who reported that their nurses ""Alway...",...,NaN,75,NaN,Not Applicable,596,NaN,16,NaN,04/01/2024,03/31/2025
1,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,H_COMP_1_SN_P,"Patients who reported that their nurses ""Somet...",...,NaN,6,NaN,Not Applicable,596,NaN,16,NaN,04/01/2024,03/31/2025
2,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,H_COMP_1_U_P,"Patients who reported that their nurses ""Usual...",...,NaN,19,NaN,Not Applicable,596,NaN,16,NaN,04/01/2024,03/31/2025
3,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,H_COMP_1_LINEAR_SCORE,Nurse communication - linear mean score,...,NaN,Not Applicable,NaN,90,596,NaN,16,NaN,04/01/2024,03/31/2025
4,010001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,H_COMP_1_STAR_RATING,Nurse communication - star rating,...,NaN,Not Applicable,NaN,Not Applicable,596,NaN,16,NaN,04/01/2024,03/31/2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,010158,RUSSELLVILLE HOSPITAL,15155 HIGHWAY 43,RUSSELLVILLE,AL,35653,FRANKLIN,(256) 332-1611,H_COMP_5_LINEAR_SCORE,Communication about medicines - linear mean score,...,NaN,Not Applicable,NaN,Not Available,83,6,16,6,04/01/2024,03/31/2025
4996,010158,RUSSELLVILLE HOSPITAL,15155 HIGHWAY 43,RUSSELLVILLE,AL,35653,FRANKLIN,(256) 332-1611,H_COMP_5_STAR_RATING,Communication about medicines - star rating,...,15,Not Applicable,NaN,Not Applicable,83,6,16,6,04/01/2024,03/31/2025
4997,010158,RUSSELLVILLE HOSPITAL,15155 HIGHWAY 43,RUSSELLVILLE,AL,35653,FRANKLIN,(256) 332-1611,H_MED_FOR_A_P,Patients who reported that when receiving new ...,...,NaN,76,6,Not Applicable,83,6,16,6,04/01/2024,03/31/2025
4998,010158,RUSSELLVILLE HOSPITAL,15155 HIGHWAY 43,RUSSELLVILLE,AL,35653,FRANKLIN,(256) 332-1611,H_MED_FOR_SN_P,Patients who reported that when receiving new ...,...,NaN,15,6,Not Applicable,83,6,16,6,04/01/2024,03/31/2025
4999,010158,RUSSELLVILLE HOSPITAL,15155 HIGHWAY 43,RUSSELLVILLE,AL,35653,FRANKLIN,(256) 332-1611,H_MED_FOR_U_P,Patients who reported that when receiving new ...,...,NaN,9,6,Not Applicable,83,6,16,6,04/01/2024,03/31/2025

In [172]:
df2 = df2.drop(columns=["Address", "City/Town", "ZIP Code", "County/Parish", "Telephone Number", "Patient Survey Star Rating Footnote", "HCAHPS Answer Percent Footnote", "HCAHPS Linear Mean Value", "Number of Completed Surveys Footnote", "HCAHPS Answer Percent", "Survey Response Rate Percent Footnote", "Start Date", "End Date"])

In [173]:
df2.head(500)

,Facility ID,Facility Name,State,HCAHPS Measure ID,HCAHPS Question,HCAHPS Answer Description,Patient Survey Star Rating,Number of Completed Surveys,Survey Response Rate Percent
0,010001,SOUTHEAST HEALTH MEDICAL CENTER,AL,H_COMP_1_A_P,"Patients who reported that their nurses ""Alway...","Nurses ""always"" communicated well",Not Applicable,596,16
1,010001,SOUTHEAST HEALTH MEDICAL CENTER,AL,H_COMP_1_SN_P,"Patients who reported that their nurses ""Somet...","Nurses ""sometimes"" or ""never"" communicated well",Not Applicable,596,16
2,010001,SOUTHEAST HEALTH MEDICAL CENTER,AL,H_COMP_1_U_P,"Patients who reported that their nurses ""Usual...","Nurses ""usually"" communicated well",Not Applicable,596,16
3,010001,SOUTHEAST HEALTH MEDICAL CENTER,AL,H_COMP_1_LINEAR_SCORE,Nurse communication - linear mean score,Nurse communication - linear mean score,Not Applicable,596,16
4,010001,SOUTHEAST HEALTH MEDICAL CENTER,AL,H_COMP_1_STAR_RATING,Nurse communication - star rating,Nurse communication - star rating,3,596,16
...,...,...,...,...,...,...,...,...,...
495,010016,SHELBY BAPTIST MEDICAL CENTER,AL,H_DOCTOR_RESPECT_A_P,"Patients who reported that their doctors ""Alwa...","Doctors ""always"" treated them with courtesy an...",Not Applicable,871,19
496,010016,SHELBY BAPTIST MEDICAL CENTER,AL,H_DOCTOR_RESPECT_SN_P,"Patients who reported that their doctors ""Some...","Doctors ""sometimes"" or ""never"" treated them wi...",Not Applicable,871,19
497,010016,SHELBY BAPTIST MEDICAL CENTER,AL,H_DOCTOR_RESPECT_U_P,"Patients who reported that their doctors ""Usua...","Doctors ""usually"" treated them with courtesy ...",Not Applicable,871,19
498,010016,SHELBY BAPTIST MEDICAL CENTER,AL,H_DOCTOR_LISTEN_A_P,"Patients who reported that their doctors ""Alwa...","Doctors ""always"" listened carefully",Not Applicable,871,19
499,010016,SHELBY BAPTIST MEDICAL CENTER,AL,H_DOCTOR_LISTEN_SN_P,"Patients who reported that their doctors ""Some...","Doctors ""sometimes"" or ""never"" listened carefully",Not Applicable,871,19

In [174]:
df2 = df2[~df2["Patient Survey Star Rating"].isin(["Not Applicable", "Not Available"])]

In [175]:
df2.shape

(28647, 9)

In [176]:
df2["Patient Survey Star Rating"] = pd.to_numeric(df2["Patient Survey Star Rating"], errors='coerce')
df2["Number of Completed Surveys"] = pd.to_numeric(df2["Number of Completed Surveys"], errors='coerce')
df2["Survey Response Rate Percent"] = pd.to_numeric(df2["Survey Response Rate Percent"], errors='coerce') #Had to change Patient Survey Star Rating to numeric so it can be used in calculations and analysis
df2["Facility ID"] = pd.to_numeric(df2["Facility ID"], errors='coerce')

In [177]:
df_merged = pd.merge(df, right=df2, left_on="Facility ID", right_on="Facility ID", how = "left")

In [178]:
df_merged.shape

(71629, 15)

In [179]:
df_merged = df_merged.rename(columns={"Facility Name_x": "Facility Name"})
df_merged = df_merged.rename(columns={"State_x": "State"})

In [180]:
print(df_merged)
print(df_merged.isnull().sum())

                         Facility Name  Facility ID State        Measure Name  \
0      SOUTHEAST HEALTH MEDICAL CENTER        10001    AL  READM-30-CABG-HRRP
1      SOUTHEAST HEALTH MEDICAL CENTER        10001    AL  READM-30-CABG-HRRP
2      SOUTHEAST HEALTH MEDICAL CENTER        10001    AL  READM-30-CABG-HRRP
3      SOUTHEAST HEALTH MEDICAL CENTER        10001    AL  READM-30-CABG-HRRP
4      SOUTHEAST HEALTH MEDICAL CENTER        10001    AL  READM-30-CABG-HRRP
...                                ...          ...   ...                 ...
71624     TEXAS HEALTH HOSPITAL FRISCO       670260    TX  READM-30-COPD-HRRP
71625     TEXAS HEALTH HOSPITAL FRISCO       670260    TX  READM-30-COPD-HRRP
71626     TEXAS HEALTH HOSPITAL FRISCO       670260    TX  READM-30-COPD-HRRP
71627     TEXAS HEALTH HOSPITAL FRISCO       670260    TX  READM-30-COPD-HRRP
71628     TEXAS HEALTH HOSPITAL FRISCO       670260    TX  READM-30-COPD-HRRP

       Number of Discharges  Excess Readmission Ratio  Number of Readmissions  \
0                     137.0                    0.9531                      13
1                     137.0                    0.9531                      13
2                     137.0                    0.9531                      13
3                     137.0                    0.9531                      13
4                     137.0                    0.9531                      13
...                     ...                       ...                     ...
71624                  41.0                    1.0483                      11
71625                  41.0                    1.0483                      11
71626                  41.0                    1.0483                      11
71627                  41.0                    1.0483                      11
71628                  41.0                    1.0483                      11

                       Facility Name_y State_y         HCAHPS Measure ID  \
0      SOUTHEAST HEALTH MEDICAL CENTER      AL      H_COMP_1_STAR_RATING
1      SOUTHEAST HEALTH MEDICAL CENTER      AL      H_COMP_2_STAR_RATING
2      SOUTHEAST HEALTH MEDICAL CENTER      AL      H_COMP_5_STAR_RATING
3      SOUTHEAST HEALTH MEDICAL CENTER      AL      H_COMP_6_STAR_RATING
4      SOUTHEAST HEALTH MEDICAL CENTER      AL       H_CLEAN_STAR_RATING
...                                ...     ...                       ...
71624     TEXAS HEALTH HOSPITAL FRISCO      TX       H_CLEAN_STAR_RATING
71625     TEXAS HEALTH HOSPITAL FRISCO      TX       H_QUIET_STAR_RATING
71626     TEXAS HEALTH HOSPITAL FRISCO      TX  H_HSP_RATING_STAR_RATING
71627     TEXAS HEALTH HOSPITAL FRISCO      TX      H_RECMND_STAR_RATING
71628     TEXAS HEALTH HOSPITAL FRISCO      TX             H_STAR_RATING

                                   HCAHPS Question  \
0                Nurse communication - star rating
1               Doctor communication - star rating
2      Communication about medicines - star rating
3              Discharge information - star rating
4                        Cleanliness - star rating
...                                            ...
71624                    Cleanliness - star rating
71625                      Quietness - star rating
71626        Overall hospital rating - star rating
71627             Recommend hospital - star rating
71628                          Summary star rating

                         HCAHPS Answer Description  \
0                Nurse communication - star rating
1               Doctor communication - star rating
2      Communication about medicines - star rating
3              Discharge information - star rating
4                        Cleanliness - star rating
...                                            ...
71624                    Cleanliness - star rating
71625                      Quietness - star rating
71626        Overall hospital rating - star rating
71627             Recommend hospital - star rating
71628                          Summary star rating

       Patient Survey Star Rating  Number of Completed Surveys  \
0                             3.0                        596.0
1                             4.0                        596.0
2                             3.0                        596.0
3                             4.0                        596.0
4                             3.0                        596.0
...                           ...                          ...
71624                         4.0                        662.0
71625                         5.0                        662.0
71626                         4.0                        662.0
71627                         5.0                        662.0
71628                         3.0                        662.0

       Survey Response Rate Percent
0                              16.0
1                              16.0
2                              16.0
3                              16.0
4                              16.0
...                             ...
71624                          14.0
71625                          14.0
71626                          14.0
71627                          14.0
71628                          14.0

[71629 rows x 15 columns]
Facility Name                    0
Facility ID                      0
State                            0
Measure Name                     0
Number of Discharges             0
Excess Readmission Ratio         0
Number of Readmissions           0
Facility Name_y                 88
State_y                         88
HCAHPS Measure ID               88
HCAHPS Question                 88
HCAHPS Answer Description       88
Patient Survey Star Rating      88
Number of Completed Surveys     88
Survey Response Rate Percent    88
dtype: int64

In [181]:
df_merged = df_merged.drop(columns=["Facility Name_y", "State_y"])
print(df_merged.shape)

(71629, 13)

In [183]:
df_merged= df_merged.dropna(subset=["HCAHPS Measure ID", "HCAHPS Question", "HCAHPS Answer Description", "Patient Survey Star Rating", "Number of Completed Surveys", "Survey Response Rate Percent"])

In [185]:
print(df_merged.shape)

(71541, 13)

In [186]:
df_merged.isnull().sum()

Facility Name                   0
Facility ID                     0
State                           0
Measure Name                    0
Number of Discharges            0
Excess Readmission Ratio        0
Number of Readmissions          0
HCAHPS Measure ID               0
HCAHPS Question                 0
HCAHPS Answer Description       0
Patient Survey Star Rating      0
Number of Completed Surveys     0
Survey Response Rate Percent    0
dtype: int64

In [190]:
import sqlite3
import pandas as pd

conn= sqlite3.connect("hospital_data.db")

df_merged.to_sql("hospitals", conn, if_exists="replace", index=False)

print("Database created successfully!")

Database created successfully!

In [193]:
query = """
SELECT State, AVG("Excess Readmission Ratio") AS avg_excess_readmission_ratio
FROM hospitals
GROUP BY State
ORDER BY avg_excess_readmission_ratio DESC
"""

result = pd.read_sql_query(query, conn)
result

   State  avg_excess_readmission_ratio
0     MA                      1.045630
1     NJ                      1.030838
2     MS                      1.028695
3     FL                      1.027853
4     IL                      1.026387
5     AL                      1.025083
6     LA                      1.024558
7     WV                      1.024004
8     NV                      1.022595
9     CA                      1.018321
10    GA                      1.018112
11    KY                      1.018098
12    PA                      1.015951
13    NY                      1.013199
14    TN                      1.012297
15    OH                      1.012032
16    AZ                      1.011042
17    SC                      1.010101
18    MI                      1.009731
19    MO                      1.008648
20    TX                      1.008597
21    AR                      1.008586
22    CT                      1.008115
23    AK                      1.007974
24    IN                      1.002347
25    RI                      0.997145
26    OK                      0.996403
27    NC                      0.995724
28    VA                      0.995346
29    NH                      0.991014
30    WI                      0.990206
31    HI                      0.989685
32    DC                      0.988381
33    MD                      0.986153
34    NM                      0.986002
35    NE                      0.985857
36    IA                      0.982292
37    MN                      0.982133
38    VT                      0.980078
39    WA                      0.973749
40    CO                      0.970531
41    DE                      0.969291
42    KS                      0.962702
43    WY                      0.962277
44    SD                      0.961893
45    ME                      0.955619
46    ND                      0.953752
47    OR                      0.950162
48    MT                      0.946466
49    UT                      0.937112
50    ID                      0.914390

In [194]:
query = """
SELECT State, AVG("Patient Survey Star Rating") AS avg_patient_survey_rating
FROM hospitals
GROUP BY State
ORDER BY avg_patient_survey_rating DESC
"""

result = pd.read_sql_query(query, conn)
result

   State  avg_patient_survey_rating
0     WI                   3.600309
1     SD                   3.570370
2     UT                   3.503268
3     AK                   3.478261
4     LA                   3.443556
5     MN                   3.405556
6     VT                   3.388889
7     NE                   3.357143
8     ME                   3.319444
9     NH                   3.306122
10    HI                   3.299145
11    ID                   3.296296
12    OR                   3.265700
13    MT                   3.236111
14    KS                   3.223443
15    KY                   3.213992
16    MS                   3.213836
17    RI                   3.199234
18    VA                   3.187887
19    OH                   3.149597
20    CO                   3.148594
21    SC                   3.148148
22    NC                   3.137885
23    AR                   3.123810
24    WY                   3.119658
25    IN                   3.109072
26    MO                   3.103509
27    OK                   3.100444
28    PA                   3.095579
29    TX                   3.093598
30    AL                   3.030864
31    IA                   3.030423
32    TN                   2.973698
33    MA                   2.968005
34    GA                   2.925774
35    WA                   2.905675
36    CT                   2.882353
37    IL                   2.858809
38    MD                   2.775541
39    DE                   2.757576
40    WV                   2.712698
41    CA                   2.670531
42    NJ                   2.646789
43    MI                   2.634146
44    FL                   2.611581
45    ND                   2.574879
46    AZ                   2.558460
47    NY                   2.552699
48    NM                   2.482385
49    NV                   2.439068
50    DC                   2.166667

In [203]:
query = """
SELECT "Measure Name", AVG("Excess Readmission Ratio") AS avg_excess_readmission_ratio
FROM hospitals
GROUP BY "Measure Name"
ORDER BY avg_excess_readmission_ratio DESC
"""

result = pd.read_sql_query(query, conn)
result

             Measure Name  avg_excess_readmission_ratio
0  READM-30-HIP-KNEE-HRRP                      1.035658
1      READM-30-CABG-HRRP                      1.028721
2      READM-30-COPD-HRRP                      1.010439
3       READM-30-AMI-HRRP                      1.010197
4        READM-30-PN-HRRP                      1.006258
5        READM-30-HF-HRRP                      1.003551

In [206]:
query = """
SELECT "Facility Name", State, AVG("Excess Readmission Ratio") AS avg_excess_readmission_ratio
FROM hospitals
GROUP BY "Facility Name"
ORDER BY avg_excess_readmission_ratio DESC
LIMIT 10
"""

result = pd.read_sql_query(query, conn)
result

,Facility Name,State,avg_excess_readmission_ratio
0,SURGICAL INSTITUTE OF READING,PA,1.30970
1,CHRISTUS CENTRAL LOUISIANA SURGICAL HOSPITAL,LA,1.30370
2,OROVILLE HOSPITAL,CA,1.28250
3,CASTLEVIEW HOSPITAL,UT,1.27060
4,MIDWEST ORTHOPEDIC SPECIALTY HOSPITAL,WI,1.26280
5,ARIZONA ORTHOPEDIC AND SURGICAL SPECIALTY HOSP...,AZ,1.25910
6,WINCHESTER HOSPITAL,MA,1.25670
7,METHODIST MCKINNEY HOSPITAL,TX,1.25510
8,SIOUX FALLS SPECIALTY HOSPITAL,SD,1.25160
9,BROWN UNIVERSITY HEALTH MORTON HOSPITAL,MA,1.21675

In [207]:
df_merged.to_csv("cleaned_hospital_data.csv", index=False)